<?php

namespace Proxies\__CG__\explorapp\PCBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuarios extends \explorapp\PCBundle\Entity\Usuarios implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Usuarios' . "\0" . 'id', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Usuarios' . "\0" . 'userName', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Usuarios' . "\0" . 'userPass', 'datosPersonales', 'negocio', 'ofertascliente');
        }

        return array('__isInitialized__', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Usuarios' . "\0" . 'id', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Usuarios' . "\0" . 'userName', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Usuarios' . "\0" . 'userPass', 'datosPersonales', 'negocio', 'ofertascliente');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuarios $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($value));

        return parent::setId($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserName', array());

        return parent::getUserName();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserName($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserName', array($value));

        return parent::setUserName($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserPass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserPass', array());

        return parent::getUserPass();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserPass($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserPass', array($value));

        return parent::setUserPass($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setDatoPersonal($datoPersonal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatoPersonal', array($datoPersonal));

        return parent::setDatoPersonal($datoPersonal);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatosPersonales()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatosPersonales', array());

        return parent::getDatosPersonales();
    }

    /**
     * {@inheritDoc}
     */
    public function getNegocio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNegocio', array());

        return parent::getNegocio();
    }

    /**
     * {@inheritDoc}
     */
    public function addNegocio($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNegocio', array($value));

        return parent::addNegocio($value);
    }

    /**
     * {@inheritDoc}
     */
    public function addOfertasCliente(\explorapp\PCBundle\Entity\OfertasCliente $ofertascliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOfertasCliente', array($ofertascliente));

        return parent::addOfertasCliente($ofertascliente);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOfertasCliente(\explorapp\PCBundle\Entity\OfertasCliente $ofertascliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOfertasCliente', array($ofertascliente));

        return parent::removeOfertasCliente($ofertascliente);
    }

}
