<?php

namespace Proxies\__CG__\explorapp\PCBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Negocio extends \explorapp\PCBundle\Entity\Negocio implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Negocio' . "\0" . 'idNegocio', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Negocio' . "\0" . 'nombreNegocio', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Negocio' . "\0" . 'direccionNegocio', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Negocio' . "\0" . 'telefonoNegocio', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Negocio' . "\0" . 'correoNegocio', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Negocio' . "\0" . 'tipoNegocio', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Negocio' . "\0" . 'idUsuario', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Negocio' . "\0" . 'ciudadNegocio', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Negocio' . "\0" . 'Usuarios', 'producto');
        }

        return array('__isInitialized__', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Negocio' . "\0" . 'idNegocio', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Negocio' . "\0" . 'nombreNegocio', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Negocio' . "\0" . 'direccionNegocio', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Negocio' . "\0" . 'telefonoNegocio', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Negocio' . "\0" . 'correoNegocio', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Negocio' . "\0" . 'tipoNegocio', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Negocio' . "\0" . 'idUsuario', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Negocio' . "\0" . 'ciudadNegocio', '' . "\0" . 'explorapp\\PCBundle\\Entity\\Negocio' . "\0" . 'Usuarios', 'producto');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Negocio $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdNegocio()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdNegocio();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdNegocio', array());

        return parent::getIdNegocio();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdNegocio($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdNegocio', array($value));

        return parent::setIdNegocio($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreNegocio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreNegocio', array());

        return parent::getNombreNegocio();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreNegocio($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreNegocio', array($value));

        return parent::setNombreNegocio($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccionNegocio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccionNegocio', array());

        return parent::getDireccionNegocio();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccionNegocio($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccionNegocio', array($value));

        return parent::setDireccionNegocio($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoNegocio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoNegocio', array());

        return parent::getTelefonoNegocio();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoNegocio($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoNegocio', array($value));

        return parent::setTelefonoNegocio($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreoNegocio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreoNegocio', array());

        return parent::getCorreoNegocio();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreoNegocio($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreoNegocio', array($value));

        return parent::setCorreoNegocio($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoNegocio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoNegocio', array());

        return parent::getTipoNegocio();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoNegocio($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoNegocio', array($value));

        return parent::setTipoNegocio($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', array());

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', array($value));

        return parent::setIdUsuario($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getCiudadNegocio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiudadNegocio', array());

        return parent::getCiudadNegocio();
    }

    /**
     * {@inheritDoc}
     */
    public function setCiudadNegocio($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCiudadNegocio', array($value));

        return parent::setCiudadNegocio($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarios', array());

        return parent::getUsuarios();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarios($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarios', array($value));

        return parent::setUsuarios($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getProducto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProducto', array());

        return parent::getProducto();
    }

    /**
     * {@inheritDoc}
     */
    public function addProducto($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProducto', array($value));

        return parent::addProducto($value);
    }

}
